<?php

namespace AppBundle\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByIdJoinedToCategory($productId)
    {
        $query = $this->getEntityManager()
        ->createQuery(
            'SELECT o, c FROM AppBundle:Offer o
            JOIN o.companyname c
            WHERE o.fkUserId = :id'
                );

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $exception) {
            return null;
        }
    }
}
