<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWhpwsns\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWhpwsns/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWhpwsns.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWhpwsns\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWhpwsns\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Whpwsns',
    'container.build_id' => '7cadf5d1',
    'container.build_time' => 1521117469,
));
