<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMtesgvx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMtesgvx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMtesgvx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMtesgvx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMtesgvx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mtesgvx',
    'container.build_id' => 'f67e90eb',
    'container.build_time' => 1521109882,
));
